name: shield

instance_groups:
- name: shield
  instances: 1
  azs:       [z1]
  vm_type:              default
  stemcell:             default
  persistent_disk_type: default

  networks: [{name: default}]

  jobs:
    - name: core
      release: shield
      provides:
        shield: {shared: true, as: shield}
      properties:
        agent:
          key: ((shield-agent-key.private_key))
        tls:
          certificate: ((shield-tls.certificate))
          key:         ((shield-tls.private_key))

    - name: shield-agent
      release: shield
      consumes:
        shield: {from: shield}

variables:
  - name: shield-agent-key
    type: rsa

  - name: shield-ca
    type: certificate
    options:
      is_ca: true
      common_name: shieldca

  - name: shield-tls
    type: certificate
    options:
      ca: shield-ca
      common_name: shield
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - "*.shield.default.shield.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: shield
  version: 7.0.2
  url: https://github.com/starkandwayne/shield-boshrelease/releases/download/v7.0.2/shield-7.0.2.tgz
  sha1: db19190e1a21336bdee5ec7ed16d4b57e456cae7
