meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: shield
    templates:
    - name: postgres
      release: shield
    - name: shield-daemon
      release: shield
    - name: shield-agent
      release: shield
    instances: 1
    persistent_disk: 2048
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))

networks: (( param "please set networks" ))

properties:
  databases:
    address: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
    databases:
    - citext: true
      name: shielddb
      tag: shield
    db_scheme: postgres
    port: 5524
    roles:
    - name: shieldadmin
      password: admin
      tag: admin

  shield:
    daemon:
      database:
        host: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
        port: 5524
        username: shieldadmin
        password: admin
        db: shielddb
    agent:
      autoprovision: http://localhost:8080
