meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: shield
    templates:
    - name: postgres
      release: shield
    - name: shield-agent
      release: shield
    - name: nginx
      release: shield
    - name: shield-daemon
      release: shield
    instances: 1
    persistent_disk: 2048
    resource_pool: small_z1
    networks: (( param "please set just_install_package networks" ))

networks: (( param "please set networks" ))

properties:
  databases:
    address: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
    databases:
    - citext: true
      name: shielddb
      tag: shield
    - citext: true
      name: sessionsdb
      tag: sessions
    db_scheme: postgres
    port: 5524
    roles:
    - name: shieldadmin
      password: admin
      tag: admin

  shield:
    schedules:
      daily: daily 3am
    retention-policies:
      short-term: 90d
    targets:
      local-bosh:
        plugin: fs
        config:
          base_dir: /tmp/from
    stores:
      local-bosh:
        plugin: fs
        config:
          base_dir: /tmp/to
    jobs:
      bosh:
        schedule:  daily
        retention: short-term
        target:    local-bosh
        store:     local-bosh

    agent:
      autoprovision: (( concat "http://shield." jobs.shield.networks.shield1.static_ips.[0] ".netip.cc" ))
    provisioning_key: (( grab properties.shield.daemon.auth.api_keys.key1 ))

    daemon:
      domain: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
      ssh_private_key: (( param "Please set the private key used by the shield daemon to talk to agents" ))
      database:
        type: postgres
        host: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
        port: 5524
        username: (( grab properties.databases.roles.0.name ))
        password: (( grab properties.databases.roles.0.password ))
        db: (( grab properties.databases.databases.0.name ))
      auth:
        api_keys:
          key1: yeah-sure-you-can-provision-stuff-whatevs
        oauth:
          sessions:
            db:
              host: (( grab jobs.shield.networks.shield1.static_ips.[0] ))
              port: 5524
              username: (( grab properties.databases.roles.0.name ))
              password: (( grab properties.databases.roles.0.password ))
              name: (( grab properties.databases.databases.1.name ))

