---
meta:
  name:    shield
  release: S.H.I.E.L.D.
  target:  shield@cloudpipes
  url:     https://cloudpipes.starkandwayne.com

  initial_version: 5.1.0
  manifest:
    path: ci/manifest.yml

  bosh-lite:
    target:   ((bosh.url))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca-certificate))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  git:
    name:  Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  github:
    owner: shieldproject
    repo:   shield-boshrelease
    branch: master
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))

groups:
- name: blobs
  jobs:
  - shield

jobs:
- name: shield
  public: true
  plan:
  - in_parallel:
    - get: git
    - get: shield
      trigger: true
      params:
        globs: [shield-server-linux-amd64.tar.gz]
  - task: update-shield
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: (( grab meta.image.name ))
          tag:        (( grab meta.image.tag ))
      inputs:
      - name: git
      - name: shield
      outputs:
      - name: pushme
      run:
        path: ./git/ci/scripts/update-blob
      params:
        REPO_ROOT:   git
        REPO_OUT:    pushme
        BLOB_DIR:    shield
        BLOB_NAME:   shield
        BLOB_BINARY: shield-server-linux-amd64.tar.gz
        BLOB_DESTINATION: shield/shield-server-linux-amd64-${VERSION}.tar.gz
        BLOB_CLEANUP:     shield/shield-server.*
        AWS_ACCESS_KEY: (( grab meta.aws.access_key ))
        AWS_SECRET_KEY: (( grab meta.aws.secret_key ))
        BRANCH:         (( grab meta.github.branch ))
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' succeeded.
        ok:      yes
        link:    (( grab meta.shout.links.build ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))
  - put: git
    params:
      rebase: true
      repository: pushme/git
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: A new version of '$BUILD_JOB_NAME' has been added to the BOSH release.
        ok:      yes
        link:    (( grab meta.shout.links.pipeline ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: Failed to push blob changes to git (for '$BUILD_JOB_NAME').
        ok:      no
        link:    (( grab meta.shout.links.build ))

- name: testflight
  serial_groups: [bosh]

resources:
- name: shield
  type: github-release
  source:
    user: shieldproject
    repository: shield
    access_token: (( grab meta.github.access_token ))
