---
meta:
  name:    shield-boshrelease
  release: S.H.I.E.L.D.
  target:  sw
  url:     https://ci.vsphere.starkandwayne.com

  initial_version: 5.1.0

  bosh-lite:
    target: https://10.58.111.44:25555

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  starkandwayne
    repo:   shield-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shield-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/shield-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/shield-boshrelease/slack:webhook" ))
    channel: '#botspam'
